break_hl2_prompt: false
subcircuits:
  "Differential Pair": "DiffPair"
  "Current Mirror": "CM"
  "Inverter": "Inverter"

categories:
  - single
  - pair

small_llms:
  - "mistral:7b-instruct"
  - "mixtral:8x22b"

medium_llms:
  - "llama3.3:70b"
  - "llama3:70b"
  - "llama3:70b-instruct"

all_llms:
  - "llama3.3:70b"
  - "llama3:70b"
  - "llama3:70b-instruct"
  - "mistral:7b-instruct"
  - "mixtral:8x22b"

eval_llms: small

benchmark_subsets:
  - small
  - medium
  - large


rule_provided: false