break_hl2_prompt: true
subcircuits:
  - "Differential Pair"
  - "Current Mirror"
  - "Inverter"

benchmark_subsets:
  - small
  - medium
  - large

categories:
  - HL1
  - HL2-CM
  - HL2-DiffPair
  - HL2-Inverter
  - HL3

opensource_llms:
  - "llama3.3:70b"

all_llms:
  - "llama3.3:70b"
  - "gpt-4.1"
  - "grok-3-beta"

eval_llm_set: opensource_llms


rule_provided: false
rule_src: null