break_hl2_prompt: true


benchmark_subsets:
  - small
  - medium
  - large

categories:
  - HL1
  - HL2
  - HL3

HL2_subcircuits:
  - "Differential Pair"
  - "Current Mirror"
  - "Inverter"

opensource_llms:
  - "llama3.3:70b"

all_llms:
  - "deepseek-reasoner"
  - "grok-3-beta"
  - "gpt-4.1"

eval_llm_set: opensource_llms


rule_provided: false
rule_src: null